### ISSUE TITLE
Mouse event for auxclick

### ISSUE THREAD

**Issue by joe-op** [purescript-web/purescript-web-uievents#18]
The auxclick ui event ([w3](https://www.w3.org/TR/uievents/#event-type-auxclick) / [mdn](https://developer.mozilla.org/en-US/docs/Web/API/Element/auxclick_event)) isn't included as a MouseEvent.  This is what Chrome and Firefox fire for middle clicks.

I had to work around this recently to get a Halogen `a` component to handle middle clicks.  If I understand correctly, auxclick would need to be here in `MouseEvent` , in purescript-indexed-dom's `MouseEvents`, and in Halogen.HTML.Events for it to integrate the same way `onClick` does.  I can make PRs for those changes if that's correct (and if auxclick fits here).

**Comment by JordanMartinez** [comment]
That sounds right. Go ahead and open up PRs for those.
