### ISSUE TITLE
InputEvent inputType missing

### ISSUE THREAD

**Issue by MonaMayrhofer** [purescript-web/purescript-web-uievents#22]
If I am not mistaken, there is currently no way of accessing the `inputType` property of an `InputEvent`.

As it is defined in the [W3C UI Events spec](https://www.w3.org/TR/uievents/#dom-inputevent-inputtype) i think it should be included in this package.

If this is actually missing, and not just hidden somewhere where I didn't look, I would be willing to try myself on a PR.

**Comment by garyb** [comment]
Yup, looks like an omission here :+1:
