### ISSUE TITLE
scroll event missing

### ISSUE THREAD

**Issue by rnons** [purescript-web/purescript-web-uievents#3]
Seems the `scroll` event is not included in this library. How to workaround?
https://developer.mozilla.org/en-US/docs/Web/Events/scroll

**Comment by garyb** [comment]
I'm not exactly sure where it should go, the event is defined in the CSSOM-view spec, so maybe `purescript-web-cssom`, but that's empty at the moment...

For now you can just use `EventType "scroll"`. There's no special type for `scroll` events, they just have the basic `Event` interface.
