### ISSUE TITLE
package install issue

### ISSUE THREAD

**Issue by jin1126** [purescript-web/purescript-web-uievents#7]
I created new empty purescript project.
Here are my step.
mkdir <folder name>
cd <folder name>
pulp init

After that I run "bower install purescript-web-uievents", but I got this error.

> Error 1 of 2:
> 
>   at bower_components\purescript-strings\src\Data\String\NonEmpty\Internal.purs line 37, column 1 - line 37, column 1
> 
>     Unable to parse module:
>     unexpected "else"
>     expecting declaration or end of input
> 
> 
>   See https://github.com/purescript/documentation/blob/master/errors/ErrorParsingModule.md for more information,  or to contribute content related to this error.
> 
> Error 2 of 2:
> 
>   at bower_components\purescript-either\src\Data\Either\Inject.purs line 16, column 1 - line 16, column 1
>     Unable to parse module:
>     unexpected "else"
>     expecting declaration or end of input
> 
> 
>   See https://github.com/purescript/documentation/blob/master/errors/ErrorParsingModule.md for more information,
>   or to contribute content related to this error.
> 
> * ERROR: Subcommand terminated with exit code 1

what should I do to install this package?

**Comment by hdgarrood** [comment]
You're using a version of the compiler which is too old. This package makes use of instance chains, which were added in v0.12.0 (release notes: https://github.com/purescript/purescript/releases/tag/v0.12.0), so you need to update to version 0.12.0 of the compiler or later.

**Comment by jin1126** [comment]
I am new to purescript so could you please let me know what should I do for upgrading my compiler version?

**Comment by garyb** [comment]
It depends how you installed it - if you used `npm` then `npm install -g purescript` should do the trick.

**Comment by jin1126** [comment]
I need to use purescript 0.11.7.
which version of purescript-web-uievents package should I use?

**Comment by garyb** [comment]
You should use this instead: https://github.com/purescript-deprecated/purescript-dom

**Comment by jin1126** [comment]
> {
>   "name": "purescript-halogen",
>   "homepage": "https://github.com/slamdata/purescript-halogen",
>   "authors": [
>     "Gary Burgess <gary.burgess@gmail.com>",
>     "John A. De Goes <john@degoes.net>",
>     "Phil Freeman <paf31@cantab.net>",
>     "Jon Sterling <jon@jonmsterling.com>"
>   ],
>   "description": "A declarative, type-safe UI library for PureScript",
>   "keywords": [
>     "purescript",
>     "halogen",
>     "ui"
>   ],
>   "repository": {
>     "type": "git",
>     "url": "git://github.com/slamdata/purescript-halogen.git"
>   },
>   "license": "Apache-2.0",
>   "ignore": [
>     "**/.*",
>     "node_modules",
>     "bower_components",
>     "test"
>   ],
>   "dependencies": {
>     "purescript-aff": "^5.0.0",
>     "purescript-avar": "^3.0.0",
>     "purescript-console": "^4.1.0",
>     "purescript-const": "^4.0.0",
>     "purescript-coroutines": "^5.0.0",
>     "purescript-dom-indexed": "^7.0.0",
>     "purescript-foreign": "^5.0.0",
>     "purescript-fork": "^4.0.0",
>     "purescript-free": "^5.0.0",
>     "purescript-freeap": "^5.0.0",
>     "purescript-halogen-vdom": "^5.1.0",
>     "purescript-media-types": "^4.0.0",
>     "purescript-nullable": "^4.0.0",
>     "purescript-ordered-collections": "^1.0.0",
>     "purescript-parallel": "^4.0.0",
>     "purescript-profunctor": "^4.0.0",
>     "purescript-transformers": "^4.1.0",
>     "purescript-unsafe-coerce": "^4.0.0",
>     "purescript-unsafe-reference": "^3.0.0",
>     "purescript-web-uievents": "^2.0.0"
>   },
>   "devDependencies": {
>     "purescript-ace": "^7.0.0",
>     "purescript-aff-coroutines": "^7.0.0",
>     "purescript-affjax": "^8.0.0",
>     "purescript-random": "^4.0.0",
>     "purescript-web-socket": "^2.0.0",
>     "purescript-assert": "^4.0.0"
>   }
> }
> 

I just got this bower.json file.
My compiler is 0.11.7 and this bower.json file contains purescript-web-uievents package.
But there is no issue when I install packages using this bower.json file.
How can I understand this?

**Comment by garyb** [comment]
Bower just fetches the PureScript source dependencies, it's only when you actually run the compiler that you'll see the error.

If you want to use that version of Halogen you'll definitely have to update your compiler. If you can't update the compiler for some reason, you'll have to use an older version of Halogen.

Be sure to remove your `bower_components` directory before attempting to install dependencies too. If the locally installed dependencies are old it will attempt and fail to resolve conflicts between what is already installed and what is in the `bower.json` file.

**Comment by jin1126** [comment]
I used to remove bower_components before installing bower packages.
For testing, I prepared one fresh machine and installed purescript 0.11.7 globally using npm and installed bower packages using above json file.
But it worked.  So I removed bower_components folder again and used my original bower.json file for installing packages. Then, it failed.
Both of them contains webui package.
It's really strange.

**Comment by jin1126** [comment]
Anyway, I will use purescript-dom. 
But I just saw that purescript-dom has no documentation on Pursuit.
Actually I need to get keyboard event on my purescript project so I was finding some reliable packages for it.
Could you please let me know which package is useful for getting keyboard event?
